### ISSUE TITLE
/f home double teleport + spam

### ISSUE THREAD

**Issue by Derpyness2000** [Aquerr/EagleFactions#68] opened 2018-04-13 10:29 UTC
Plugin version: The custom unfinished 0.9.13 you gave me a few days ago
Sponge version: Spongeforge 1.12.2-2611-7.1.0-BETA-3017

Upon using /f home you get teleported to your faction home, a few seconds later it teleports you to there again and then you get spammed until you relog http://prntscr.com/j4pep8

**Comment by TomTheHero** [comment] 2018-04-13 10:30
I used the wrong account for a sec but whatever xD

**Comment by TomTheHero** [comment] 2018-04-13 10:32
And i also suggest a /f delhome incase you want to remove your faction home

**Comment by Aquerr** [comment] 2018-04-13 15:09
Damn, I will look at this today.

**Comment by Aquerr** [comment] 2018-04-13 21:11
Alright, so, the issue is fixed now but I need to correct some things before I upload the new file. I will try to do it tomorrow.

**Comment by Aquerr** [comment] 2018-04-15 13:35
@TomTheHero Here it is --> [EagleFactions-1.12.2-0.9.13pre](http://www.mediafire.com/file/cydyy5ha6dj4maz/EagleFactions-1.12.2-v0.9.13.jar) 

This file includes one new command for managing faction's flags/privileges. Try it out by typing `/f flags` 😄

I will consider adding `/f delhome` command. Right now, if you want to remove a faction's home, just remove it from the **factions.conf** file in the **data** folder.

**Closed** 2018-04-15 18:38 UTC
Labels: 1.12.2, Fixed, bug
